### ISSUE TITLE
Error in install generator

### ISSUE THREAD

**Issue by samuelpismel** [mudbugmedia/critical-path-css-rails#19]
With a fresh install of rails 4.2.8 i got this error:

`rails generate critical_path_css:install`

``` console
[WARNING] Could not load generator "generators/critical_path_css/install_generator". Error: uninitialized constant CriticalPathCss::Rails::Generators.
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/critical-path-css-rails-1.0.0/lib/generators/critical_path_css/install_generator.rb:4:in `<module:CriticalPathCss>'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/critical-path-css-rails-1.0.0/lib/generators/critical_path_css/install_generator.rb:3:in `<top (required)>'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:332:in `block (2 levels) in lookup'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:328:in `each'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:328:in `block in lookup'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:327:in `each'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:327:in `lookup'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:138:in `find_by_namespace'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/generators.rb:155:in `invoke'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/generate.rb:13:in `<top (required)>'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:50:in `generate'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
/home/samuel/www/teste/bin/rails:9:in `<top (required)>'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/samuel/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Could not find generator 'critical_path_css:install'. Maybe you meant 'integration_test', 'scaffold_controller' or 'active_record:model'
Run `rails generate --help` for more options.
```
Gemfile:

``` ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.8'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'critical-path-css-rails', '~> 1.0.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

```

**Comment by samuelpismel** [comment]
The same with Rails 5.1.4

**Comment by michael-misshore** [comment]
@samuelpismel, Thanks for reporting this. It looks like one of the forks has a fix for this. I'll try to get this rolled in ASAP.

**Comment by julien51** [comment]
Same here! Good luck with the merge!

**Comment by michael-misshore** [comment]
Version 1.0.1 has been released to fix this issue.
