### ISSUE TITLE
Deployment with capistrano  - Rake Task fails

### ISSUE THREAD

**Issue by ck2000** [mudbugmedia/critical-path-css-rails#49]
I am trying to deploy using the asset pipeline. I am receiving the following message:

> Tasks: TOP => deploy:assets:precompile
> (See full trace by running task with --trace)
> The deploy has failed with an error: Exception while executing as xxxx : rake exit status: 1
> rake aborted!
> NoMethodError: undefined method `[]' for nil:NilClass
> [...]/shared/bundle/ruby/2.6.0/gems/critical-path-css-rails-4.0.1/lib/critical_path_css/rails/config_loader.rb:36:in `validate_css_paths'
> [...]/shared/bundle/ruby/2.6.0/gems/critical-path-css-rails-4.0.1/lib/critical_path_css/rails/config_loader.rb:7:in `initialize'
> [...]/shared/bundle/ruby/2.6.0/gems/critical-path-css-rails-4.0.1/lib/critical-path-css-rails.rb:35:in `new'
> [...]/shared/bundle/ruby/2.6.0/gems/critical-path-css-rails-4.0.1/lib/critical-path-css-rails.rb:35:in `config_loader'
> [...]/shared/bundle/ruby/2.6.0/gems/critical-path-css-rails-4.0.1/lib/critical-path-css-rails.rb:31:in `fetcher'
> [...]/shared/bundle/ruby/2.6.0/gems/critical-path-css-rails-4.0.1/lib/critical-path-css-rails.rb:13:in `generate_all'
> [...]/releases/20190823144812/lib/tasks/critical_path_css.rake:6:in `block (2 levels) in <top (required)>'
> [...]/releases/20190823144812/lib/tasks/critical_path_css.rake:18:in `block in <top (required)>'
> [...]/shared/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
> [...]shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
> [...]/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'

What am I doing wrong? Iam using ruby 2.6.3 and rails 5.2.3

**Comment by michael-misshore** [comment]
@ck2000 I'm pretty sure we don't have a test case for manifest_name, which is what you are using. I think the OP fixed this in his fork, but I'll need to write a test for this, duplicate the error, and then push the fix.

**Comment by ck2000** [comment]
Okay, please let me know if I can give you a helping hand. Having this fixed in the master branch makes sense.
